name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Required to push to GHCR

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and tag Docker image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/my-image-name
        TIMESTAMP=$(date +%s)
        docker build . --file Dockerfile --tag $IMAGE_ID:$TIMESTAMP --tag $IMAGE_ID:latest

    - name: Push Docker image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/my-image-name
        docker push $IMAGE_ID:$TIMESTAMP
        docker push $IMAGE_ID:latest
