name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Required to push to GHCR

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3 # Use v3 for latest features and fixes
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 # Recommended for building Docker images

    - name: Build and tag Docker image
      id: docker_build # Add an ID to this step to access outputs
      run: |
        IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/shaiyar"
        # Use a more reliable and consistent timestamp for tagging
        # For pushes to main, use the short SHA as part of the tag, and also 'latest'
        # For pull requests, use the short SHA only (no 'latest' to avoid overwriting production tags)
        if [[ "${{ github.event_name }}" == "push" ]]; then
          TAG_SUFFIX="latest,${{ github.sha }}"
        else
          TAG_SUFFIX="${{ github.sha }}"
        fi
        
        # Use full SHA for unique tag, and also a short SHA (first 7 chars) for convenience
        FULL_TAG="${{ github.sha }}"
        SHORT_TAG="${{ github.sha }}"
        
        # Output the tags for use in subsequent steps
        echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
        echo "full_tag=$FULL_TAG" >> $GITHUB_OUTPUT
        echo "short_tag=${SHORT_TAG::7}" >> $GITHUB_OUTPUT # Get first 7 characters for short tag

        docker build . \
          --file Dockerfile \
          --tag "$IMAGE_NAME:$FULL_TAG" \
          --tag "$IMAGE_NAME:${SHORT_TAG::7}" \
          --tag "$IMAGE_NAME:latest" # Only tag as latest on push to main
          
    - name: Push Docker image
      run: |
        IMAGE_NAME="${{ steps.docker_build.outputs.image_name }}"
        FULL_TAG="${{ steps.docker_build.outputs.full_tag }}"
        SHORT_TAG="${{ steps.docker_build.outputs.short_tag }}"
        
        docker push "$IMAGE_NAME:$FULL_TAG"
        docker push "$IMAGE_NAME:$SHORT_TAG"
        
        # Only push 'latest' tag for pushes to main branch
        if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
          docker push "$IMAGE_NAME:latest"
        fi
